### ISSUE TITLE
assets precompileって一体何？

### ISSUE THREAD

**Issue by ryouzi** [TECH-CAMP-GEEKS/ruby_on_rails#11]
普段何気なくコマンドを実行しているけど、assets precompileって一体何をしているの？

**Comment by sainu** [comment]
アセットパイプラインで管理されているerb, sass, coffeeファイルをコンパイルして、一枚に圧縮することだと認識しています

**Comment by TakefumiYamamura** [comment]
あとコンパイルする際にダイジェストを付加することで、ファイルが更新されたときのみキャッシュをブラウザにとりにいくことを可能にさせる→無駄な再キャッシュを避けて高速化してくれる、も大きな役割だと思ってる。

**Comment by 5oya** [comment]
アセットファイル（HTML に付随するファイル達）を連結したり圧縮することで効率的にアクセスできるようにするフレームワーク

jsやcssって複数ファイルに分けて管理していると思うけど、それをそれぞれ一つのファイルにすることでブラウザからのリクエストを減らしてくれる。
また、文法上必要のない空白を削除したり、変数名を1文字にするなどの圧縮をしてサイズ自体を少なくしている。

**Comment by sainu** [comment]
ほぼ回答が出揃った感じがする

**Comment by 5oya** [comment]
全員のAnswerを合わせて回答となります。

**Comment by ryouzi** [comment]
こりゃcloseですね

**Comment by sainu** [comment]
次田さんらの見解も聞きたかった

**Comment by sainu** [comment]
👍 が過半数集まればcloseしましょ

**Comment by ryouzi** [comment]
rails 4になってから rails 3のときよりプリコンパイルの速度は約2.5倍早くなったらしい

**Comment by 5oya** [comment]
rails4から優秀になったんだ！！

**Comment by ryouzi** [comment]
Rails5はどの程度改善されたのでしょうね

**Comment by TakefumiYamamura** [comment]
rubyのガベージコレクタ周りで高速化された記事を見てた時に書いてた！

**Comment by sainu** [comment]
rails5はフレームワークとして取り残されないように、最新技術を取り入れた感がありますね

**Comment by ryouzi** [comment]
関係ないけどhttp/2
http://blog.redbox.ne.jp/http2-cdn.html
