### ISSUE TITLE
schema.rbやGemfile.lockはリモートにプッシュしていいのか問題

### ISSUE THREAD

**Issue by ryouzi** [TECH-CAMP-GEEKS/ruby_on_rails#3]
shema.rbやGemfile.lockをプッシュするとあまりよくないと聞くことが多いが何がどうよくないのか詳細にはわかっていないかも。

**Comment by sainu** [comment]
両方プッシュしてます

**Comment by sainu** [comment]
gemfile.lockはプロジェクトで使っているgemが書かれており、bundle installはそれを見るので、
仮にサーバーでbundle installをした場合、ローカルと同じgemのバージョンを使うために必要ですよね。
チーム開発をする時も同様です。プロジェクトごとにgemのバージョンを決めて、それを他の人も使用しないと、環境ごとに違うバージョンのgemを使ってしまう可能性があります。

**Comment by sainu** [comment]
schema.rbに関してもプッシュします。
結局railsはschema.rbを見てデータベースの状況を把握しているので、最新のデータベース状況を表すschema.rbはリモートリポジトリに存在するべきです。

**Comment by ryouzi** [comment]
schema.rbはプッシュしないとDBとの齟齬が起きてエラーが起こる可能性があるからプッシュするけど、Gemfile.lockはそのPCの環境に依存しているからプッシュしてはいけないような気がする。
少し調べてみる。

**Comment by ryouzi** [comment]
Gemfile.lockについて
http://ylang365.hatenablog.com/entry/2014/01/07/143704
状況により変わるらしい。

**Comment by ryouzi** [comment]
Gemfile.lockについて
http://normalse.hatenablog.jp/entry/2015/11/14/135835
AWSのEC2でインストールできたgemがMacでは入らなかったことがある。.

**Comment by sainu** [comment]
gemfile.lockをプッシュしない場合って、世界中のどの規格のPCを持っているかわからない人たちが使う可能性がある完璧オープンソースでのプロジェクトでですよね。。。
普通の会社やチームでの開発ではさほどPCの性能的に違いがないから問題ないように思えます。

**Comment by sainu** [comment]
ほげええ、そんなことがあるんですね。EC2がlinux環境でなかったとか。

**Comment by tsugitta** [comment]
Rails3で書かれたアプリはRails4では動かない（こともある）し、逆も然りなわけなので、ライブラリのバージョンは固定しておかないとアップデートされた際に動かなくなってしまうことがありますよね。
なのでGemfile.lockによりしっかりとバージョンを固定させておくというのがかなり広く支持されている方法だと思います👀
環境によって入るgem入らないgemとかがあることがあるとしても、それよりも上記の問題の方が極めて致命的なので別の対処をすべきだと思いますね！

**Comment by tsugitta** [comment]
schema.rbも常にpushすべきだと思いますね〜　よく出されるのが此方の記事：http://techracho.bpsinc.jp/hachi8833/2014_02_07/15390
