### ISSUE TITLE
ActiveRecord::RelationとActiveRecord::Baseの違いを説明してください

### ISSUE THREAD

**Issue by sainu** [TECH-CAMP-GEEKS/ruby_on_rails#4]
RelationとBaseクラスのそれぞれの大きな特徴的な違いって何ですか？

**Comment by TakefumiYamamura** [comment]
レコード一行を取り扱うクラスがbaseでレコードを複数行扱うクラスがRelationって個人的には思ってる。
だからUserテーブルとかがあったときにwhereとかfindとか複数行のレコードをもとに何か取得する系がActiveRecordRelationで　user.name とか 一行のレコードに対して処理を行うメソッドがActiveRecordBaseのメソッドといえるんじゃないかな

**Comment by tatsuki-m** [comment]
だいたいは、そのような解釈で問題ないかと思う。

もう少し厳密にみてみると、メソッドチェーンができるActiveRecord::Relationオブジェクトを返すもの。的な解釈っぽいけどね。
英語ができなさすぎて悲しい。。。。

[参考URL](http://railscasts.com/episodes/239-activerecord-relation-walkthrough?view=asciicast): 

```
The Relation Class
Having queries return an ActiveRecord::Relation object allows us to chain queries together and this Relation class is at the heart of the new query syntax. 
 Let’s take a look at this class by searching through the ActiveRecord source code for a file called relation.rb.
```

**Comment by junjungoal** [comment]
findはrelationではありませんね。
ActiveRecord::Relationの中には連鎖的にメソッドチェーンできるメソッドが入っているということで、オブジェクトはたつきさんが言うようにActiveRecord::Relationオブジェクトを、返します。
このオブジェクトを返すことにより、ActiveRecord::Relationクラスのインスタンスメソッドを連鎖的使えるようになるわけですね。

ちなみに、whereとかを記述したタイミングではActiveRecord::Relationを返すだけで実際にはこの時点で検索は行わないようですね。
参考URL:  http://www.atmarkit.co.jp/ait/articles/1104/12/news135_2.html

まあそういうわけで、find とかfind_byはメソッドチェーンが出来ないのでRelationではないっていう分け方ができます。

**Comment by TakefumiYamamura** [comment]
いや すくなくともfind_byはrelationなはず　http://www.mitchcrowe.com/10-most-underused-activerecord-relation-methods/　
（findは自身ない笑）
メソッドチェーンが行えるものが　ActiveRecordRelationのインスタンスで、ActiveRecordRelationのインスタンスに対して処理を行えるのがRelationのメソッド、,メソッドチェーンを行えなかった時点でBaseのインスタンスでそれに対して処理を行うのがBaseのメソッドってのがすっきりするのかなぁ

**Comment by junjungoal** [comment]
Doc見る限りないですね… 

http://api.rubyonrails.org/classes/ActiveRecord/Relation.html

**Comment by TakefumiYamamura** [comment]
たしかに、、、ただここwhereとかもないから、全部はのってないみたいだね

**Comment by junjungoal** [comment]
find_by はActiveRecord::FinderMethodsですね、
http://apidock.com/rails/ActiveRecord/FinderMethods/find_by

**Comment by junjungoal** [comment]
いやすみません、find_by relationぽいです… ちょっともう少し調べてみます。

**Comment by TakefumiYamamura** [comment]
返り値が何かであるかよりも、レシーバがリレーションかbaseかに依存するとおもた。
でもってリレーションのインスタンスがレシーバだとメソッドチェーンができるってのが論理関係すっきりなのかなぁ

**Comment by junjungoal** [comment]
とりあえず、activerecordのソースみます。 そっちの方が早いので。

**Comment by junjungoal** [comment]
基本的に、findメソッドとかすべてActiveRecord::Relationのインスタンスメソッドとしてlib/relation/以下のファイルに全て定義されている。なので基本的に返すものはそれぞれ違えど、ActiveRecord::Relationのインスタンスに対しては何でも実行できる。

```
#<User  xxxxxxxxx id: 1, email: hoge@gmail.com > こんなインスタンスがあったら
User.where(email: hoge@gmail.com).class #=> User::ActiveRecord_Relation
User.where(email: hoge@gmail.com).find(1) #=>  #<User xxxxx....... 
```

上記のwhereメソッドはActiveRecord::Relationを返すので、これに対してActiveRecord::Relationクラスのインスタンスメソッドであるfindも使えてしまうのですね。
返すものはメソッドによるので注意しないとですね。

ただどうやら

```
User.find(xx)
```

みたいにクラスに対してfindやwhereが使えてしまいますが、これはactive_record/base.rb でextend してるからのようです。

結局ActiveRecord::Relationはfindやwhereなどの検索系のメソッドを基本的に定義しているものといったもので、ActiveRecord::Baseはもともといろいろなクラスやモジュールをincludeやextendしていて、その一つとしてActiveRecord::Relationで定義してあるものをextendしてActiveRecord::Baseを継承したクラスに対しても直接使えるようにしているといった感じですね。

@sa-inu  微妙な回答ですが...どうでしょう

**Comment by tsugitta** [comment]
とても勉強になりますね、

ActiveRecord::BaseはまさにActiveRecordを利用したモデルのベースクラスで、これを継承することにより、そのモデルはActiveRecordの振る舞いを獲得することができ、
ActiveRecord::RelationはActiveRecordの操作により得られた、「複数のActiveRecord::Baseを継承するインスタンス」を表す概念である
といった感じなんでしょうね〜

・いずれもQuery系のモジュールを取り入れているのでallとかfindとか使える
・ActiveRecord::Relationはキャッシュが効く
・返り値云々
といったあたりは二次的な違い感がありますね

**Comment by sainu** [comment]
とっっっっっっっっても勉強になりました
@junjungoal わかりやすい解説ありがとう！それを参考に自分でもActiveRecord読んでみます
@tsugitta より細かい２次的な違いを提示してくださってありがとうございます！
みなさんのおかげでとっても良いドキュメントになりました！感謝ですm(__)m

closeします
