### ISSUE TITLE
バックグラウンドで非同期処理させるgem

### ISSUE THREAD

**Issue by sainu** [TECH-CAMP-GEEKS/ruby_on_rails#5]
http://techracho.bpsinc.jp/kazumasa-ogawa/2014_09_25/17541

**Comment by sainu** [comment]
表では通常通りアプリを動かしていて、バックグラウンドでスクレイピングをしているんだが、
そのスクレイピングを終わったらフラッシュメッセージを出したい。
どうやって実装したら良いですか？

**Comment by IzumiSy** [comment]
通知の処理はSocket.IOがいいですね

**Comment by sainu** [comment]
@IzumiSy 泉さん！ご意見いただきありがとうございます！

早速見てみます！
