### ISSUE TITLE
ActiveRecord::Baseのインスタンスからインスタンス変数の値を取り出す方法で[:key]と.keyの違いは？

### ISSUE THREAD

**Issue by sainu** [TECH-CAMP-GEEKS/ruby_on_rails#8]
ActiveRecord::Baseのインスタンスからインスタンス変数の値を取り出す方法で疑問があります。

Articleのカラムにtitleってあった時、
Article.find(1).titleって方法が普通ですが、
Article.find(1)[:title]でも取れるかと思います。

インスタンスにハッシュの記述が使えるのはなぜですか？
誰か教えてください><

**Comment by yuta-t** [comment]
ハッシュ記法的なメソッドが使えるよう定義されてるから

違いとしては、ActiveRecord::Baseに定義してある、[:hoge]メソッドの定義と、
ActiveRecord::Baseに.hogeを定義するメソッドの定義を見ると良さそう

**Comment by sainu** [comment]
あざっす
