### ISSUE TITLE
データベースのバックアップ方法のベストプラクティスを教えて！

### ISSUE THREAD

**Issue by sainu** [TECH-CAMP-GEEKS/ruby_on_rails#9]
データベースの情報を定期的にバックアップとりたいです。
個人的にはdb/csvフォルダ内にcsvファイルで保存するのかなって思うのですが、いかがでしょう？
herokuで運用しているのでなるべくアプリ容量は減らしたいです。

誰か教えてください！

**Comment by ryouzi** [comment]
バックアップってherokuの外に置いた方がいいよね、、、？

**Comment by tsugitta** [comment]
herokuでアプリが作成したファイルは多分次サーバが眠った時に消えるので外部に置くことになりますね

ec2とかであれば、cronでmysqlのdumpを走らせてS3なりに上げるのが一番低負荷で速そうですが、herokuはそうもいかないのでmysql dumpに相当するアドオンを探すか、無ければそういった処理をRubyで書いてcronに相当するアドオンから走らせる感じなのかなと

**Comment by ryouzi** [comment]
TECH::CAMPのDBのバックアップとることになったから、いいことがわかり次第共有します

**Comment by sainu** [comment]
キーター
ありがとうございます

**Comment by ryouzi** [comment]
http://qiita.com/yoshiso/items/e48126c2feaf747f3b25
これがいいらしい

**Comment by ryouzi** [comment]
gem 'backup'
gem 'whenever'
のgemを使ってS3に保存するのが流行りらしい。

http://post.simplie.jp/posts/33

**Comment by ryouzi** [comment]
http://blog.digital-squad.net/article/202435240.html
こちらも同じような記事

**Comment by 5oya** [comment]
なるほど。定期的にバックアップをとるのね

**Comment by ryouzi** [comment]
http://kzy52.com/entry/2014/01/18/125446

**Comment by ryouzi** [comment]
backupのgem?はbundlerの管轄外なのでbundle execやSettingsなどは使うことができない。

**Comment by ryouzi** [comment]
```
backup perform --trigger  mysql_backup --config_file 'config/<filename>'
```

などでバックアップを実行する

**Comment by ryouzi** [comment]
本番DBだとなぜかbackupコマンドが効かないので以下のように対応した

```
gem install backup
backup generate:model --trigger mysql_backup --databases='mysql' --storages='s3'
Backup/models/mysql_backupにバックアップの記述
backup perform --trigger  mysql_backup
```

これでバックアップは取れる。
あとはwheneverでパスを指定してあげればよろしいかと。
